name: tit
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  device_info_plus: ^9.0.3
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  package_info_plus: ^4.1.0

  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  location: ^5.0.3
  image_picker: ^1.0.2
  photo_view: ^0.14.0
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  flutter_screenutil: ^5.8.4
  flutter_onboarding_slider: ^1.0.9
  flutter_svg: ^2.0.7
  flutter_native_splash: ^2.3.2
  crypto : ^3.0.1
  json_annotation: ^4.8.1
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.2
  google_api_availability: ^5.0.0
  firebase_core: ^2.15.0
  connectivity_plus: ^4.0.2
  cached_network_image: ^3.2.3
  image_cropper: ^5.0.0
  permission_handler: ^11.0.0
  flutter_image_compress: ^2.0.4


  #QR
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0

  # Analytics Tool
  firebase_analytics: 10.4.5

  # Auth
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  flutter_facebook_auth: ^6.0.1

  flutter: 
    sdk: flutter




dev_dependencies: 
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/svg/
  uses-material-design: true

