name: tit_ti_too
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5


  device_info_plus: ^9.0.3



  permission_handler: ^10.4.3
  path_provider: ^2.1.0

  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  location: ^5.0.3
  image_picker: ^1.0.2
  photo_view: ^0.14.0
  google_sign_in: ^6.1.4
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  flutter_screenutil: ^5.8.4
  flutter_onboarding_slider: ^1.0.9


  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

